### ISSUE TITLE
Complete travis-ci.org integration

### ISSUE THREAD

**Issue by grahammiln** [capitainetrain/stations#5]
Travis provides free [continuous integration](http://en.wikipedia.org/wiki/Continuous_integration) for public GitHub hosted projects.

**After merging #3 an administrator needs to complete the following steps to connect GitHub and Travis for capitainetrain**

# Adding Travis Support

Travis requires administrator rights to the github repository. This is [not ideal](http://docs.travis-ci.com/user/github-oauth-scopes/) and a known limitation of GitHub's API.

To reduce the risk of problems and to allow security breaches to dealt with easily, isolate Travis support:

1. Create a new GitHub user account called `capitainetrain-robot`
1. Give `capitainetrain-robot` administrator rights to **only** the projects to test.
1. [Associate capitainetrain with Travis](http://docs.travis-ci.com/user/getting-started/) through `capitainetrain-robot` 

In case of future problems, the `capitainetrain-robot` account can be isolated and administrator rights revoked.

## Adding Build Status

Once Travis has been set-up, a build status graphic can be embedded within capitainetrain's read me file. The graphic will looking something like:

[![Build Status](https://travis-ci.org/DrawKit/DrawKit.png?branch=master)](https://travis-ci.org/DrawKit/DrawKit)

The markdown for a graphic like this is:

    [![Build Status](https://travis-ci.org/capitainetrain/stations.png?branch=master)](https://travis-ci.org/capitainetrain/stations)

**Comment by paulRbr** [comment]
It has been done (see https://github.com/capitainetrain/stations/pull/2) thanks

**Comment by espadrine** [comment]
Thanks a lot! I added the badge, too ☺

**Comment by Tristramg** [comment]
Thanks. So everything is done? can this issue be closed?

**Comment by paulRbr** [comment]
@Tristramg yes everything is fine you can close this issue.
