### ISSUE TITLE
GeoJSON edition

### ISSUE THREAD

**Issue by grahammiln** [capitainetrain/stations#7]
# GeoJSON Edition

A GeoJSON edition of the database would help track down station coordinate problems and highlight missing stations. See [stations.geojson](https://github.com/grahammiln/stations-geojson/blob/master/stations.geojson) for an example:

![sample-map](https://cloud.githubusercontent.com/assets/278765/7316546/1b7270fe-ea78-11e4-8f79-576d4c0f7d29.jpg)

## Include or Keep Separate ?

[grahammiln/stations-geojson](https://github.com/grahammiln/stations-geojson) contains a script to convert the station's database to GeoJSON format.

I am not sure if this script should become part of **stations** or remain separate in **stations-geojson**.

**Comment by espadrine** [comment]
It would be great to include such a script! However, the current language in use in this repository is Ruby, so writing those scripts in Ruby would be cleaner. You can put those scripts under a `tools/` folder in the repository.

**Comment by grahammiln** [comment]
Thank you.
